Django/hola/Aerolinea/urls.py
from django.urls import path
from . import views

app_name = 'aerolinea'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    ]

Django/hola/Viernes/urls.py
from django.urls import path
from . import views

app_name = 'viernes'

urlpatterns = [
    path('indice/<str:date>', views.indiceParam, name='indice'),
    path('indice', views.indice, name='indice')
    ]

Django/hola/alarmas/urls.py
from django.urls import path
from . import views

app_name = 'alarmas'

urlpatterns = [
    path("",views.index, name='index'),
    path("v2", views.v2, name="v2"),
    ]

Django/hola/hola/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Principal/', include('Principal.Urls')),
    path('Viernes/', include('Viernes.urls')),
    path('alarmas/', include('alarmas.urls')),
    path('Aerolinea/', include('Aerolinea.urls')),
]

Django/hola/Aerolinea/models.py
from django.db import models

# Create your models here.

class Flight(models.Model):
    origin = models.CharField(max_length=64)
    destination = models.CharField(max_length=64)
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: De {self.origin} a {self.destination} tardas {self.duration}"

Django/hola/Aerolinea/views.py
from django.shortcuts import render
from .models import Flight

# Create your views here.

def index(request):
    return render(request, 'Aerolinea/index.html', {"flights": Flight.objects.all()})

def flight(request, flight_id):
    flight = Flight.objects.get(id=flight_id)
    return render(request, 'Aerolinea/flight.html', {'flight': flight})
    

Django/hola/Principal/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def holaDjango(request):
    return HttpResponse("Hola Django!")

def pepe(request):
    return HttpResponse("Hola Pepe!")

def holaTu(request, nombre):
    return HttpResponse(f'Hola {nombre.capitalize()}!')

def indice(request):
    return render(request, 'Principal/index.html')

def indiceParam(request, nombre):
    return render(request, 'Principal/saludo.html', {'nombre': nombre.capitalize()})

Django/hola/Viernes/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def indiceParam(request, date):
    return render(request, 'Viernes/Dia.html', {'date': date.capitalize()})

def indice(request):
    return render(request, 'Viernes/Negacion.html')
    

Django/hola/alarmas/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse 

def index(request):
    if "alarmas" not in request.session:
        request.session["alarmas"] = ['6:50', '7:00']
    return render(request, 'alarmas/index.html',{'alarmas':request.session["alarmas"]})

def v2(request):
    if request.method == 'POST':
        form = FNuevaAlarma(request.POST)
        if form.is_valid():
            alarma = form.cleaned_data['alarma']
            request.session["alarmas"] += [alarma]
            return HttpResponseRedirect(reverse('alarmas:index'))
        else:
            return render(request, 'alarmas/v2.html', {'cont_form': form})
    else:
        return render(request, 'alarmas/v2.html', {'cont_form':FNuevaAlarma()})

class FNuevaAlarma(forms.Form):
    alarma = forms.CharField(label='Programar alarma')
    #snooze = forms.IntegerField(label='Repetir', min_value=0, max_value=0)

Django/hola/Aerolinea/templates/aerolinea/flight.html
{% extends "aerolinea/layout.html" %}
{% block body %}
    <h1>Vuelo {{flight.id}}</h1>
    <ul>
        <li> Origen: {{flight.origin}}</li>
        <li> Destino: {{flight.destination}}</li>
        <li> Duración: {{flight.duration}}</li>
    </ul>
    {% endblock %}

Django/hola/Aerolinea/templates/aerolinea/index.html
{% extends "aerolinea/layout.html" %}
{% block body %}
<h1>Vuelos</h1>
<ul>
    {% for flight in flights %}
    <li>
        <a href="{% url 'aerolinea:flight' flight.id %}"> Vuelo {{flight.id}}: de {{flight.origin}} a {{flight.destination}}
        </a>
    </li>
    
    {% endfor %}
</ul>
{% endblock %}

Django/hola/Aerolinea/templates/aerolinea/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Vuelos</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

Django/hola/alarmas/templates/alarmas/index.html
{% extends "alarmas/layout.html" %}
{% block body %}
    <h1>Alarmas del sistema</h1>
    <ul>
        {% for alarma in alarmas %}
            <li>{{ alarma }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'alarmas:v2' %}">Agregar nueva alarma</a>
{% endblock %}

Django/hola/alarmas/templates/alarmas/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Alarmas!</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

Django/hola/alarmas/templates/alarmas/v2.html
{% extends "alarmas/layout.html" %}
{% block body %}
        <h1>Nueva alarma</h1>
        <form action="{% url 'alarmas:v2' %}" method="post">
            {% csrf_token %}
            {{ cont_form }}
            <input type="submit">
        </form>
        <a href="{% url 'alarmas:index' %" name="alarma" value="Enviar">Ver alarmas</a>
{% endblock %}